// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svdgniviotecguehvtig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2ZGduaXZpb3RlY2d1ZWh2dGlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NTE5ODAsImV4cCI6MjA1MzEyNzk4MH0.X6V8bw0SX-ZppIeIL6tXhqiXTej2shzJJ2PNxICWe8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);